[build]
command = "npm run netlify:deploy"
publish = "dist/FindMovies/browser"

[[redirects]]
from = "/documentation/*"
to = "/documentation/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[plugins]]
package = "@netlify/angular-runtime"
